[package]
name = "cef_app"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
cef = { workspace = true }
winit = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { workspace = true }
